### ISSUE TITLE
Incorrect tag 2025.05.16

### ISSUE THREAD

**Issue by avalentino** [umr-lops/xradarsat2#18]
If my understanding is correct the tag should be 2023.05.16 (not 2025.05.16).

**Comment by yreynaud** [comment]
Yes, your understanding is good. It is due to a mistake, the correct tag is 2023.05.16. The tag 2025.05.16 has been marked has broken (like you can see here https://anaconda.org/conda-forge/xradarsat2/files), so normally it isn't downloaded when searching for the latest version. I don't know why is it already displayed on the conda-forge feedstock ( https://github.com/conda-forge/xradarsat2-feedstock ) that the version is 2025.5.16.

If I correctly answered your issue, can I close the issue?

**Comment by avalentino** [comment]
Well, it would be nice if you could rename the tag in git (see e.g. https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag)
In my case I have a script to monitor new releases and it looks at the https://github.com/umr-lops/xradarsat2/tags page.

**Comment by yreynaud** [comment]
Issue has been solved there : https://github.com/conda-forge/xradarsat2-feedstock/pull/19

**Comment by avalentino** [comment]
Sorry, I have just realised that the incorrect tag is still there.
@yreynaud could you please remove it?

**Comment by sebastic** [comment]
Please delete the erroneous tag: `git push <remote> :2025.05.16`

New releases are hidden behind this higher version.
